/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gameboard } from "./Gameboard";
export * as factories from "./factories";
export { Gameboard__factory } from "./factories/Gameboard__factory";
